### ISSUE TITLE
Can not Assess Some Web Sites 

### ISSUE THREAD

**Issue by speedforce-lk** [AliAlmasi/vless-cf-worker#1]
i setup your vless with cloudflare
it works great I can bypass all websites
except the cloudflare ones
like the cloudflare
1,1,1,1
speedtest
they didn't load up

**Comment by AliAlmasi** [comment]
Hello there.
I have reviewed the code. I don't see any problem with the code. I think it's kind of a rule that's been set by the cloudflare itself.
I'm still researching to find out the problem, but I think this is all cloudflare's fault.

**Comment by AliAlmasi** [comment]
> nice code. It's not the code's fault
yeah.. Some websites will block cloudflare’s IP.

Thanks. Yeah, It's actually pretty obvious when you use another proxy instead of a Cloudflare-based proxy to access a website which blocks Cloudflare's IP ranges.

**Comment by AliAlmasi** [comment]
I'm gonna close this issue as there's no way to fix this. If anyone reading this has a way to fix this problem, comment here or contact me.

**Comment by AliAlmasi** [comment]
I'm gonna close this issue as there's no way to fix this. If anyone reading this has a way to fix this problem, comment here or contact me.
