### ISSUE TITLE
Can't access to Cloudflare routed domains

### ISSUE THREAD

**Issue by ParhamzXc** [AliAlmasi/vless-cf-worker#2]
can't resolve cloudflare ipv6 domains, it can be fixed by a nat64/dns64 service, this enables ipv6 icmp ping results translates to ipv4
where to put [nat64prefix::DecimalCloudflareIP] in json script? which line is proxyIP configuration?

**Comment by AliAlmasi** [comment]
> where to put [nat64prefix::DecimalCloudflareIP] in json script? which line is proxyIP configuration?

Honestly, I don't understand what is your problem. I reviewed the code and I didn't see any bugs or anything that may have caused this problem.

I guess you have the same problem as #1 issue, it's either cloudflare's fault or the site that you're trying to visit.

**Comment by AliAlmasi** [comment]
Since no response was received from you, I'm gonna close this issue.
